### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by berendkleinhaneveld** [pygfx/pygfx#255]
During work on [pygui](https://github.com/fork-tongue/pygui) I needed WorldObjects/Meshes to be able to handle events, so I made a subclass of Mesh to be able to handle events such as 'onClick'. Would be great to have built-in support for events instead. 
We might want to think about what kind of events to support. And which kind of objects can fire/handle events (WorldObject, Renderer?, Canvas?).

**Comment by Korijn** [comment]
Also see #186 with similar needs

**Comment by Korijn** [comment]
What does threejs do?

**Comment by Korijn** [comment]
Firstly, I think we can agree that it would be useful to give WorldObject an event handling system [just like you did](https://github.com/fork-tongue/collagraph/blob/014452cd79da6f336de59ed8169bceeab24f1ab6/collagraph/renderers/pygfx_renderer.py#L8-L23).

Additionally, I think in order to enable decoupled interaction handling (e.g. on click, choosing between camera interaction, picking, and transformation, and potentially more), we should implement a mechanism similar to [event propagation in browsers](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Examples#example_5_event_propagation).

Taking for example on mouse down:

* Request picking info from renderer
* Dispatch event to world object under cursor
* Iterate over parents and keep dispatching the event to each of them
* Event handlers can prevent the event from propagating further
  * Something like `event.stopPropagation()` or just `return True`

List of examples that you can then implement in a decoupled fashion:

* A TransformControl to be first to receive the event, and stop propagation
* Camera interaction to be handled at the root if no sub world object has already handled it
  * Could be Scene or maybe even one step further up, the Canvas
* Things to light up ('on hover') without stopping propagation, you can implement this independently then from dragging for example

**Comment by berendkleinhaneveld** [comment]
I agree with your proposal.
> Stop propagating up at Scene (WorldObject graph root) or also go up one more step to Canvas?
Let's go all the way to 11 and take it to canvas! 
> Introduce an event object so we can set flags like event.stopPropagation() and event.preventDefault() or just return True to stop propagation?
Let's introduce that event object: if we ever want to support more complex event handling, then it will be handy to have in place already.

**Comment by Korijn** [comment]
> > Stop propagating up at Scene (WorldObject graph root) or also go up one more step to Canvas?
> 
> Let's go all the way to 11 and take it to canvas!

Just me mindful that you may need to implement part of this in wgpu-py then.

**Comment by almarklein** [comment]
> Stop propagating up at Scene (WorldObject graph root) or also go up one more step to Canvas?

The scene will only get the event if an actual world object is under the mouse, so that's no use to the camera. We would also need a mouse-grab mechanism so that world objects keep getting move events during a drag even if the mouse is no longer over it. 

> Introduce an event object so we can set flags like event.stopPropagation() and event.preventDefault() or just return True to stop propagation?

I'm in favor of `stopPropagation`, because using `return True` might get iffy if a handler delegates to another function. Maybe we can use the current event dict and do something like `event["stop_propagation"] = True`?

**Comment by Korijn** [comment]
> The scene will only get the event if an actual world object is under the mouse, so that's no use to the camera.

If nothing is picked, we can just dispatch the event to the root, right? Seems like that would be no issue.

> We would also need a mouse-grab mechanism so that world objects keep getting move events during a drag even if the mouse is no longer over it.

Isn't that an application level concept though? I don't see how an event system could offer that.

**Comment by berendkleinhaneveld** [comment]
> Maybe we can use the current event dict and do something like event["stop_propagation"] = True?

I was just looking at the [Event JavaScript reference](https://developer.mozilla.org/en-US/docs/Web/API/Event) for some inspiration. What I could do is try to mimic that as much as possible (for the parts that we actually need), in order to make it familiar at least to people who have any experience with JavaScript events. The nice part about using an object for an event is that you can make it clear which parts are supposed to be read-only and which are not.

But simply using an object instead of a dict breaks compatibility with the [jupyter_rfb](https://jupyter-rfb.readthedocs.io/en/latest/events.html) spec. But I could create a `to_dict()` method or implement `__getitem__(self, key)` to make it kind of behave like a dict?

**Comment by almarklein** [comment]
> Isn't that an application level concept though? I don't see how an event system could offer that.

Well, this is how it works in the browser :)

**Comment by Korijn** [comment]
> > Isn't that an application level concept though? I don't see how an event system could offer that.
> 
> Well, this is how it works in the browser :)

Can you link to MDN docs for that behaviour? I don't recall ever seeing that.

**Comment by almarklein** [comment]
https://w3c.github.io/uievents/#event-type-mousemove

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3015475/157867718-20a67dfe-a22d-40cd-893c-87b0dc963d6c.png">

**Comment by Korijn** [comment]
> https://w3c.github.io/uievents/#event-type-mousemove
> 
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/3015475/157867718-20a67dfe-a22d-40cd-893c-87b0dc963d6c.png">

That's referring to the boundary of the user agent. Not the DOM elements (or WorldObjects in our case), right?

**Comment by berendkleinhaneveld** [comment]
I think generally it should be up to the application to implement 'mouse-grabbing' behaviour but I also see that this notion kind of interferes with how the gizmo works (though I haven't looked at it in detail yet). 
Maybe we can think of something to facilitate mouse-grabbing behaviour to applications in a way that also allows the gizmo to hook into that? If the canvas is processing the events, that seems like a good place to register mouse-grabbing event handlers or something like that.

**Comment by berendkleinhaneveld** [comment]
Leaving this here as reference to what Almar was talking about: https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture

**Comment by almarklein** [comment]
> Well, this is how it works in the browser :)

No it does not. I stand corrected.

**Comment by berendkleinhaneveld** [comment]
Proposal:

## Changes to wgpu
    
* Refactor events to be objects (maybe with a dict-like interface for compatibility with jupyter event system) (unless you guys favour dicts over class/object for this?)
* Model event objects after the web spec:
    * Add `stop_propagation()` and `prevent_default()` (and some others such as `bubbles`, `cancelable`, etc)
    * Add 'target' attribute to events
* Expose a mixin: `EventTarget` that can be used by pygfx / others to easily add event handlers to objects
* Canvas handles events that have a `target` set differently:
    * First, the target gets an opportunity to handle the event
    * If a target (`EventTarget`) has a parent and the event is still 'bubbling', then the parent gets to handle the event
    * If an `EventTarget` has 'captured' the mouse events, then this object will get to handle events instead

## Changes to pygfx

* Add `EventTarget` mixin from wgpu to `WorldObject`
* Similar to controls, add something like `add_default_event_handlers()` to `WgpuRenderer`. This way, the renderer can pick the scene on mouse/key events. When there is an item under the mouse, it will generate a new Event for the canvas to handle with the same type, but with picking info and the `target` set to the item under the mouse.
* Update camera / controls
* Update gizmo

(I'll update this comment with any suggestions)

I'm not sure yet if we want to have different subclasses of `Event`, such as `MouseEvent`, `KeyboardEvent`, etc. But I guess we'll find out soon enough. Also depends on whether you guys think it is a good idea to use an object instead of dict.

**Comment by almarklein** [comment]
An object is friendlier to work with, which would be nice in pygfx/arbiter, but in wgpu-py I like the dict for being generic, without forcing a specific system on whatever is build on top. I wonder if an approach is possible where we keep wgpu-py mostly as it is, and implement this more fully fledged system in pygfx, e.g. by converting/wrapping the dicts into a nicer object.

Maybe something along these lines:
* We create a standard function that can be set as a callback on a canvas (listening to all events).
* On a canvas event, the root handler converts to a pygfx-event, picks the object under the mouse, and bubbles the event. If not handled, it will be delivered to the *root object*.
* Tools like the Gizmo can bind to events on world-objects, and prevent propagation.
* Controllers bind to the *root object*.

I don't know yet what the root object should be in this approach. Two observations:
* The code that registers the root handler must know both the canvas and the renderer. I think the canvas itself would be tricky, because it should not know about the renderer. It could be the renderer, because it already has a ref to the canvas. Or it could be that each app/example has to do a manual call.
* The *root object* can be anything, but it's handy if it's something that controllers already need. Could be the renderer too.

**Comment by berendkleinhaneveld** [comment]
So if we look at it in responsibilities:

* `wgpu-py` will be generating the 'system' events (plain dicts), for each of the auto-gui frameworks: GLFW, Qt, jupyter.
* `pygfx` will be intercepting those events, and convert into its own 'system' (with propagation and such).

This might indeed need (almost?) no changes to `wgpu-py` I guess. Let me whip something up to see what that could look like.
