### ISSUE TITLE
Colorspace Management and Gamma Correction

### ISSUE THREAD

**Issue by panxinmiao** [pygfx/pygfx#361]
We have discussed colorspace and gamma correction before, but I think we have not fully clarified it.

In the current code, we assume that the shader receives the color in the srgb space, and uses `srgb2physical()` to convert the color to the linear space when "the code deems it necessary". (including diffuse maps, environment maps, and so on).  

However, there are some problems here.

First of all, some texture maps themselves exist in linear space. For example, HDR environment maps in RGBE format are usually stored in linear space. Although we have the `colorspace` attribute in the `Texture` class, at present only the colorspace of the diffuse texture map (the `map` attribute of the `Material`) works. Others, such as environment maps, use `srgb2physical()` for conversion by default after sampling, which is often incorrect when using HDR environment maps.

In addition, strictly speaking, colorspace conversion after sampling is not correct. The process of sampling (using linear filtering mode) is accompanied by interpolation. We use a linear space texture format (such as `rgba8unorm`) to transfer the actual srgb space image and sample it. This sampling and interpolation process actually takes place in the srgb space (which is not what we expect), and then perform space conversion on the sampled results. The same is true for mipmap generation. The correct generation process should also occur in the linear space. For the original image in the srgb space, we only need to set the GPU texture format to the "-srgb" format (for example, `rgba8unorm-srgb`), and everything will be completed automatically.

In my opinion, all colors in the renderer logic should be assumed to be colors in linear space, which is the working space of the renderer and also helps to simplify and unify the rendering code. Otherwise, we must carefully distinguish which color values come from the linear space and which color values come from the srgb space in the rendering logic, which is usually troublesome and may be accompanied by a large number of flags.

For static colors, we should complete the management and conversion of colorspace in the CPU process to ensure that when input to the GPU or shader, it is in linear space.  And generally speaking, colorspace conversion only needs to occur once on the cpu, and does not need to occur in every draw and every fragment as it does now.

For texture maps, the format of `GPUTexture` should be set according to the encoding format (linear or srgb) of the texture map itself (we are likely to use textures from different colorspaces at the same time in the same renderer). This can not only achieve the logical unification (making the encoding or colorspace of the `gfx.Texture` class correspond to the format of `GPUTexture`), but also use hardware acceleration to directly conduct correct linear sampling from the srgb texture.

Finally, I think we'd better provide the function of specifying the output texture format (maybe through the attribute of the renderer) by user. Although in most cases, we should output textures in `rgbaunorm8-srgb` format, there are some exceptions. For example, when generating a dynamic environment map from the scene, this process occurs inside the program. We only need to generate the texture in the linear space and hand it over to the following rendering logic, without any additional colorspace conversion process. For another example, when rendering the "depth" image, we can also specify the output texture format as `rgba32float` or `depth32float` to ensure the depth accuracy.

**Comment by almarklein** [comment]
Interesting points! Thanks for bringing these up 👍   I took the liberty of responding in a different order than you mentioned these points. Starting with the simpler ones:

> Others, such as environment maps, use srgb2physical() for conversion by default after sampling, which is often incorrect when using HDR environment maps.

Good point. This would need to be fixed whatever we do. I'll make a list at the end of this post.

> For example, when generating a dynamic environment map from the scene, this process occurs inside the program. We only need to generate the texture in the linear space and hand it over to the following rendering logic, without any additional colorspace conversion process. 

We could make this settable, but I think you nearly always want an srgb texture, because it will make more effective use of the available bits. If you store linear colors in an 8bit per color texture, you'll observe bands in dark regions.

Now that I think of it, when this texture is used again in the following rendering logic, the `srgb2physical` should not be called (currently it is, I think).

Coming to the harder points ...

> In my opinion, all colors in the renderer logic should be assumed to be colors in linear space, which is the working space of the renderer

I believe the starting point should be what would be an API that's easiest for the users (and powerful enough where needed). Then we can look at where best to do the conversion. Preferably in the most consistent possible way.

I believe, by now, that we cannot simply decide that all colors coming into the shader are all either srgb or linear. The `colorspace` attribute is the current exception. But when going for all-colors-are linear, there will also be exceptions. To name a few:

* The BackgroundMaterial has 4 colors which are interpolated (in srgb, deliberately) over the viewport.
* Similarly 1D colormaps (think Vidirids or Jet) should be interpolated in srgb.
* I guess any texture depicting "artist" colors is best interpolated in srgb.
* Per-vertex colors.

> In addition, strictly speaking, colorspace conversion after sampling is not correct.

Good point! I had not thought of texture interpolation yet. Although as the list that I mention above implies: I do think it depends :)

Another aspect is that I want a user to load in an image or volume without having them worry whether it's srgb or not. If they show that data as-is, it is interpreted as srgb (because it's likely correct), but if they use a colormap, the value is interpreted as just a value, that is used as an input into the colormap. This means that we cannot put the data in an srgb colormap by default.

So let me propose something ...

* We replace/tweak the `Texture.colormap` option so that it can do:
   * Convert using `srgb2physical` when the data is interpreted as a color. Also the current default. (Interpolation is in sRGB space.)
   * Mark texture as linear, so `srgb2physical` is not called. (Interpolation is in physical space.)
   * Mark texture as srgb format, for people who *know* their texture is an srgb color. Conversion done in hardware. (Interpolation is in physical space.)
* The `get_bindings` part of the shader is aware of the texture flag, and maybe also of the colorspace of other input, and can set a template variable, similar to what we do in the current mesh shader. That way the shader stays "clean".
* Where it makes sense in the shader, we make srgb colors explicit using a prefix, to improve readability.

Another way to see this is that users who know what they're doing set the `colorspace` of all textures to either `physical` or to use an `-srgb` texture. People who know less about this will get the default behavior, which is actually pretty good in most cases. What do you think?

## To fix

* The `Texture.colorspace` attribute is only honored for the `.map` texture.
* The `srgb2physical` should not be made for textures that we know are in srgb format (e.g. output from another renderer).
* Make it possible for the render target to be not srgb?

**Comment by almarklein** [comment]
Addition: Initially, my thinking was that since for the user most colors are sRGB, it would make sense that the colors come into the shader as sRGB. But becuase we can't really draw a clean line anyway, I think a good rule of thumb would be to convert to physical space as quickly as possible. So I agree with your suggestion to convert static colors on the CPU (except the ones that are interpolated with other colors).

**Comment by panxinmiao** [comment]
Yes, I think that all colorspace management and conversion are completed outside the shader (in CPU part), which will bring many benefits.  For color, conversion is done in the CPU phase, and for texture, it is achieved by setting the correct GPUTexture format.

We agree that all colors in the shader (whether from uniform or from the texture) are colors in linear space. In other words, we treat them as color values in linear space, no matter what color values they are actually. The colorspace management is handed over to the CPU.

>I believe the starting point should be what would be an API that's easiest for the users (and powerful enough where needed).

>Another aspect is that I want a user to load in an image or volume without having them worry whether it's srgb or not. 

I quite agree.

But it has little to do with where to manage the colorspace. We can reduce the user's work in this aspect by setting the default value or default behavior of "satisfying the requirements of being correct in most scenarios".

For experienced users who understand colorspace, they have the ability to make correct settings in their own code. For inexperienced users, in most cases, the default settings can meet their needs, and they do not need to care about the colorspace. In some cases, when they find that the rendering results do not meet their expectations, we can provide complete documents for them to quickly find the reasons, so that they can learn about the colorspace. ——In my opinion, if users need some advanced rendering or design work, this is what they must know.

**Comment by almarklein** [comment]
> We agree that all colors in the shader (whether from uniform or from the texture) are colors in linear space. In other words, we treat them as color values in linear space, no matter what color values they are actually. The colorspace management is handed over to the CPU.

To be clear, I don't fully agree with that :)  I believe there are valid use-cases where interpolation in sRGB is preferred. And there are practical advantages for having a default texture format that does the sRGBtophysical conversion in the shader.

This means that in the shader, where a color is loaded, some care must be taken. I see no way around this. By making generalizations and using suffixes we can make it clear what happens.

I'll prep a PR following the proposal I posted earlier, including some of your suggestions. May be a while though - I'll probably finish text rendering first.

> For inexperienced users, in most cases, the default settings can meet their needs, [...] when they find that the rendering results do not meet their expectations, we can provide complete documents for them to quickly find the reasons, so that they can learn about the colorspace. [...]

I agree 👍

**Comment by Korijn** [comment]
@almarklein  Did we already do this?

**Comment by almarklein** [comment]
Yes, we have colorspace management implemented that allows working both with srgb and physical colors.
