### ISSUE TITLE
Ability to scale camera-axii individually

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#388]
It would be useful to have a way to automatically scale the camera to fill a world object on the canvas, for example if we plot a sine wave with small amplitudes it barely shows up unless the camera is scaled appropriately. Doing this automatically would be useful for dynamic scientific plots! I think I can add this functionality to `camera.show_object()` and `controller.show_object()`, but I couldn't figure out how to map from canvas coordinates to world coordinates w.r.t. the camera.

```python3
import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx


canvas = WgpuCanvas()
renderer = gfx.WgpuRenderer(canvas)

scene = gfx.Scene()
xs = np.linspace(0, 30, 100)
ys = np.sin(xs) / 10
zs = np.ones(100)

positions = np.dstack([xs, ys, zs])[0].astype(np.float32)

line = gfx.Line(
    gfx.Geometry(positions=positions),
    gfx.LineMaterial(thickness=2.0, color=(1, 1, 1, 1)),
)
scene.add(line)

camera = gfx.OrthographicCamera()

controller = gfx.PanZoomController()
controller.add_default_event_handlers(renderer, camera)

controller.show_object(camera, line)

def animate():
    controller.update_camera(camera)
    renderer.render(scene, camera)


if __name__ == "__main__":
    canvas.request_draw(animate)
    run()
```

![image](https://user-images.githubusercontent.com/9403332/202877925-132fa314-1aa1-4dd9-8612-18dd14e137a5.png)

if you set `camear.scale.y = 0.1`:

![image](https://user-images.githubusercontent.com/9403332/202877934-9fd8878e-d290-401e-a84b-941056d84a99.png)

**Comment by Korijn** [comment]
If you search for `project` in the linalg subpackage you can find utilities to map coordinates between view space and screen space.

I'm not entirely sure if scaling is the right way to go about this though. I would expect a plotting library to:

* Allow users to explicitly set the domain per axis
* Otherwise fallback to computing the domain per axis by finding the extrema of the input data

And then with the known domain per axis, you can set up an orthogonal camera directly and adjust top/bottom/left/right to match the domain.

I.e. if the x axis domain is -50 to 80, that's what I would feed into the orthogonal camera's left/right settings.

**Comment by kushalkolar** [comment]
Thanks for the comments! Some questions:

1. Yup this will be implemented. 
2. Yes, the purpose of computing domain per axis is if the user is interactively changing the data in a scene. For example clicking a datapoint in `SceneA` which changes a lineplot in `SceneB`, but these lineplots can vary in orders of magnitude. Do you suggest creating a new camera set the viewport to render with this new camera rather than scaling the existing one? Are previous cameras garbage collected if they're no longer in use by a viewport?

By the way we will be developing fastplotlib quite a bit in December, would you (and/or Almar) be interested in chatting with us in early December for input on how to use pygfx most optimally?

**Comment by Korijn** [comment]
You can update the viewport of a given camera and update the projection matrix, no need to create a new one. Is that helpful?

Yes I am available for a chat on fastplotlib, I'm pretty excited about it!

**Comment by almarklein** [comment]
> And then with the known domain per axis, you can set up an orthogonal camera directly and adjust top/bottom/left/right to match the domain.

This discussion is very much related to #356. Right now, the `OrthographicCamera` has a width and height. It maintains the aspect ratio, by applying a viewport that fits *at least* the box indicated by width and height. Further it has a zoom factor.

My suggestion for #356 would be to:
* get rid of the zoom factor, zooming changes width and height instead.
* Introduce `maintain_aspect` prop (#356 already does this). This will also allow zooming to adjust width and height individually instead of together. 
* I'd guess that `camera.show_object()` then becomes rather easy to do.

> By the way we will be developing fastplotlib quite a bit in December, would you (and/or Almar) be interested in chatting with us in early December for input on how to use pygfx most optimally?

Sure!
