### ISSUE TITLE
Improvements to camera, controller, and display

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#403]
I was working on a text example with `show` and ran into several annoyances related to cameras. I figured I'd list these, along with existing related issues, and then do a proper camera/controller refactoring soon.

* When providing a camera to `Display`, it should use not update the view, because I already carefully set the initial view.
* The zoom for an `OrbitController` on a `OrthographicCamera` is broken, it should set the bounds when `Controller.zoom_changes_distance` is set.
* Make `PanzoomController` work with a perspective camera. 
* Use `@property`'s.
* #388. A start was made in [#356](https://github.com/pygfx/pygfx/pull/356), but it seems a bit stuck on some of the above issues.
* #113
* #231
* #300 (but also allow user to determine when to draw)
* Automatically update the camera ~(but also allow users to determine when it happens)~.

 Also a proposal: a controller is in most cases already directly associated with a specific camera because of `add_default_event_handlers`. My proposal is to make the wrapping explicit, and drop the need to call `update_camera` on each draw. I think this will simplify both internal and user code. Needs some though on the edge cases for controlling multiple camera's, but we'll figure that out.

----

Most work was done in #457. Here are the leftovers:

* [x] Trackball controller.
* [x] Fly controller.
* [x] #365
* [x] Make key-mouse-bindings configurable.
* [x] Better default bindings? (e.g. panning is not consistent).

**Comment by Korijn** [comment]
As long as all the coupling happens one way, I'm OK with your proposed changes.

So that means, Camera should _not_ need to change to accomodate Controller requirements, but the other way around is fine.

Another way to put it: Controllers depend on the Camera API, but Cameras do not depend on the Controller API.

That's a crucial invariant to me for the architecture.

**Comment by almarklein** [comment]
> Another way to put it: Controllers depend on the Camera API, but Cameras do not depend on the Controller API.

Completely agree; a camera knows nothing about a controller.

**Comment by Korijn** [comment]
Some minor notes:

> * [Controller does not request draw on load_state #300](https://github.com/pygfx/pygfx/issues/300)

I'm fairly certain there will be users who will want to use controllers in their applications, _and_ maintain full control when a draw is requested. Of course it's the polar opposite of users who just want to throw a controller into a script and not worry about the details. But I think both use cases should be supported. Otherwise the first user group will end up having to reimplement controllers just so they can keep control over draw requests.

> Also a proposal: a controller is in most cases already directly associated with a specific camera because of `add_default_event_handlers`. My proposal is to make the wrapping explicit, and drop the need to call `update_camera` on each draw. I think this will simplify both internal and user code. Needs some though on the edge cases for controlling multiple camera's, but we'll figure that out.

The same duality applies. Some users will be happy that the cameras are updated automatically in response to event handlers, others will want to exercise control themselves. Let's make sure both use cases are supported.

**Comment by almarklein** [comment]
Using this issue to track remaining points. See top comment.
