### ISSUE TITLE
Remove "plot_" prefix from examples?

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#411]
The plot prefix is a mechanism from Sphinx-gallery to select examples for inclusion in the gallery. We now also have
`# sphinx_gallery_pygfx_render = True`, which we can set to `False`, right? And the prefix can (I assume) be set to an empty string?

cc @FirefoxMetzger

**Comment by FirefoxMetzger** [comment]
Unfortunately no, because they do different things. 

`plot_` (or any other prefix we can choose) tells sphinx-gallery that the file contains plots and that it should eval each code block and pass the output to the scraper.

`# sphinx_gallery_pygfx_render = True` instructs our scraper to generate an image for the current block that it is provided with. This defaults to `False` and is evaluated for each block. You can have multiple images in one example and - in this case - you would have multiple `# sphinx_gallery_pygfx_render = True` comments in the same file (one for each location where a plot should be generated).

If we add `# sphinx_gallery_pygfx_render = True` in a file without the `plot_` prefix then sphinx will never pass the code to our scraper and we won't render anything. Similarly, we need to have some prefix, because we want to ignore examples that are too expensive to render in CI or that target specific backends unavailable in CI.

**Comment by almarklein** [comment]
So a file starting with `plot_` but that has `# sphinx_gallery_pygfx_render = True` will still be run, as in setting up the viz, but it won't render?

**Comment by FirefoxMetzger** [comment]
> So a file starting with plot_ but that has # sphinx_gallery_pygfx_render = True will still be run, as in setting up the viz, but it won't render?

Do you mean `# sphinx_gallery_pygfx_render = False`? Yes. A file with a `plot_` but no instructions to generate images will be executed in full, but no output will be captured.

**Comment by almarklein** [comment]
Sorry, yes I meant it to be `False`. Thanks for the clarification.
