### ISSUE TITLE
PyInstaller hooks needed

### ISSUE THREAD

**Issue by berendkleinhaneveld** [pygfx/pygfx#454]
When bundling pygfx with PyInstaller into an application, there are some data files and some dynamic libs missing.

We need to bundle:

* dynamic libs of `freetype` (collect_dynamic_libs)
* data from `pygfx.pkg_resources` (collect_data_files)

I noticed that when just using `collecting_data_files("pygfx.pkg_resources")` results in a name clash with `pkg_resources` module from setuptools. We might consider replacing the use of `pkg_resources` with `importlib.resources`?

**Comment by Korijn** [comment]
> * dynamic libs of `freetype` (collect_dynamic_libs)

At least within the pygfx library, we can and should only provide a hook for pygfx' resources. Freetype needs to get a hook of its own, or a hook can be contributed to to the pyinstaller community hooks.

> * data from `pygfx.pkg_resources` (collect_data_files)

If anyone wants to take a shot at this, please adopt the modern approach we also applied in wgpu-py. It includes unit testing on CI. Note that it's only run as part of one testing job (py3.9 I believe) since it's a little slow to run that test.

https://github.com/pygfx/wgpu-py/tree/main/wgpu/__pyinstaller

(Modern here means that hooks can be included in packages themselves, and unit tested. Previously all hooks would live inside pyinstaller which introduces a lot of maintenance churn as you can probably imagine).

> I noticed that when just using `collecting_data_files("pygfx.pkg_resources")` results in a name clash with `pkg_resources` module from setuptools. We might consider replacing the use of `pkg_resources` with `importlib.resources`?

I don't have a problem with that.

**Comment by almarklein** [comment]
I agree that it's probably easiest (also on the long term) to implement the approach that we use in wgpu-py. This then needs to be applied in pygfx and also contributed to [freetype-py](https://github.com/rougier/freetype-py).

As for the name clash, would renaming the directory to just `resources` (as in wgpu) help?

**Comment by berendkleinhaneveld** [comment]
> As for the name clash, would renaming the directory to just `resources` (as in wgpu) help?

Yes, that would work for now.

The freetype problem actually stems from a path/resource lookup that expects the path at a certain location relative to the original source file, which doesn't take into account packaged applications: https://github.com/rougier/freetype-py/blob/51ee6e15e6d7b3a9ca0f5e96b11bfa8c07575c36/freetype/raw.py#L32
It seems that the dynamic library is already found by PyInstaller but it is moved to the root of the bundled package, hence the lookup fails. So it might suffice to have freetype make use of the following snippet:
```python
is_frozen = getattr(sys, "frozen", False)
if is_frozen:
    package_root = Path(sys._MEIPASS)
else:
    package_root = Path(__file__).parent.resolve()
```

**Comment by Korijn** [comment]
Here's freetype: https://github.com/rougier/freetype-py/pull/162
