### ISSUE TITLE
Best way to show basic UI elements

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#519]
What is the best way to have basic within-canvas UI elements, for example right-click menus, tooltips with text (or maybe even world objects inside them?). They could be created with simple box meshes but I'm wondering if that's the best approach. Is this something which could be within `pygfx` or only downstream? Either way I can try to make some examples if the box mesh approach is the best way to do it.

**Comment by almarklein** [comment]
The plane geometry would be even better so create 2D rectangles. I can also imagine that a UI-lib manages a single Mesh object containing multiple rectangular shapes, which would be lighter than many loose planes. I'd recommend abstracting this, so that the implementation can later be changed without affecting the UI API.

**Comment by Korijn** [comment]
You can investigate imgui, it may be relatively easy to integrate with pygfx. Imgui is renderer agnostics, it just generates triangles that you need to render yourself, I believe.

**Comment by kushalkolar** [comment]
Thanks for the ideas! imgui particularly looks nice. I'll take a deeper look when I have time.

**Comment by kushalkolar** [comment]
@Krande

Thanks for your interest! Korijn posted some ideas here: https://github.com/pyimgui/pyimgui/issues/336

**Comment by kushalkolar** [comment]
panxinmiao added this to wgpu a while ago, examples in the wgpu repo: https://github.com/pygfx/wgpu-py/blob/main/examples/imgui_basic_example.py
