### ISSUE TITLE
Implementing an API to map / unmap buffers

### ISSUE THREAD

**Issue by hmaarrfk** [pygfx/pygfx#666]
I was tracing down some of our slowdowns for our application, at times we have up to 200MB of texture data being updated every frame in approximately 9MB chunks, and I found that a pretty variable delay (100ms - 200 ms) was occuring in updating texture data that needed changing.

https://github.com/pygfx/pygfx/blob/22ab65925cfb19540b2dbb953d875ba4e9dce8a2/pygfx/renderers/wgpu/_renderer.py#L522-L523

Looking through your code, it seems like it you all had outlined the possibility of mapping / unmapping buffers from WGPU to improve performance. (Option A below). My understanding is: 
* Once "mapped" the buffer can be written to by the CPU.
* Once "unmapped" the buffer can be fetched by the GPU.

https://github.com/pygfx/pygfx/blob/22ab65925cfb19540b2dbb953d875ba4e9dce8a2/pygfx/renderers/wgpu/_update.py#L71-L83

I'm wondering if you have any plans to implement it, or any cautionary tales as to why it would be a bad idea to implement it within the context of Python.

My vision would be that if it were mapped, it would be "exposed" as a numpy array of the appropriate shape and size.

The larger challenge is that this operation (renderer.flush) occurs when holding the Qt lock... so the whole application "freezes" during the transfer when you let it occur in the "animate" loop (as it is implemented today). I'm giving this context if this helps brainstorm an other approach. 

Thanks for the advise.

cc: @kingbedjed

**Comment by hmaarrfk** [comment]
xref: https://github.com/pygfx/wgpu-py/blob/b54f628c59f0be89c4b61046a28c4ce380e8ae22/tests/test_wgpu_native_texture.py#L99

I had also found this skeleton of a test that I wanted to include as reference for the discussion.

**Comment by Korijn** [comment]
You should review the GPUBuffer class in wgpu-py, it'll probably give you some more insight

**Comment by hmaarrfk** [comment]
I'm sad to say that I didn't realize that textures used a different code path. 

I'm trying to see if there is a similar API but it seems that textures are "more complicated" than simple buffers. 

Maybe in my application I can reduce the textures to buffers???

**Comment by hmaarrfk** [comment]
I’ve somewhat decided to abandon this strategy since it isn’t in my interests in the long term. 

I’ve resorted to doing some CPU side mipmapping

**Comment by hmaarrfk** [comment]
I think the discussion in #600 likely covers the same principles, and I don't want to dilute it. thanks for the pointers. Reading them really helped!

**Comment by Korijn** [comment]
Just sharing some more thoughts; you mention uploading 200MB of texture data each frame? I suppose it's some sort of video footage?

You could upload texture data for multiple frames initially (the amount of frames would be called your "buffer size" even though we're working with textures here), and then continuously stream upload the next bunch of frames in a separate thread, before you actually need to render them.

This methodology is called out-of-core rendering, since the entirety of the data does not fit in the GPU, you have to stream the data in and out of the GPU on demand with some kind of heuristic to predict which data is needed in the future, and which data can be discarded.

In this case it sounds like you are implementing video playback so the heuristic is quite simple.

Please correct me if I'm wrong. It sounds like this is what you'll need to do since your data is so extremely large.

**Comment by hmaarrfk** [comment]
Thanks for the pointer. Sounds like an interesting concept. 

ill see how we can use these ideas throughout our development!!!!
