### ISSUE TITLE
Weird shadow flicker

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#678]
Saw it in look_at.py example. Not sure if other examples are affected too.

**Comment by kushalkolar** [comment]
I can reproduce this.

**Comment by almarklein** [comment]
@panxinmiao anything that pops to mind what this could be?

**Comment by panxinmiao** [comment]
> Findings so far:
> 
> * I have not found any other affected examples.
> * The flicker disappears when using a pointlight instead of a directional light.
> * The `light_directional_shadow.py` also has a directional light, but I cannot get it to flicker.
> 
> 🤔

It's a bit strange, I'll investigate it.

**Comment by panxinmiao** [comment]
Simple record of my investigation process here:

1. Observed shadows constantly appearing and disappearing every other frame.(Use `disp = gfx.Display(canvas=WgpuCanvas(max_fps=1))`, It can be easily observed.)
2. Use `RenderDoc` to record the rendering process, found that every other frame, the shadow depth map was not generated correctly.
3. Print `light.shadow.camera.matrix`, value found to be changing every frame.
4. Further investigation revealed that `light.shadow.camera.local.rotation` was changing every frame.
5. Suspected that there was a bug in the `look_at` method for calculating the pose, because in the example, the direction of the light and the `up` direction were parallel, and I suspected that this case was not being handled correctly.
6. Modified example, slightly adjusted direction of parallel light(`sun.local.position = (0, 3000, 1)`), and the bug disappeared, confirming that suspicion 5 was correct.
7. Traced code and located issue in `forward setter` method of `transform`.

**Comment by almarklein** [comment]
Impressive work @panxinmiao !
