### ISSUE TITLE
Double click event triggers only once

### ISSUE THREAD

**Issue by schlegelp** [pygfx/pygfx#741]
Hi. I noticed that the double click event seems to only ever be triggered once.

Here's a minimal example to reproduce: you should see `"double_click"` printed to the console the first time you double click but not for any subsequent double clicks. 

```python
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx

canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()
camera = gfx.OrthographicCamera()
controller = gfx.PanZoomController(camera, register_events=renderer)

def animate():
    renderer.render(scene, camera)
    canvas.request_draw()

def trigger(event):
    print(event.type)

if __name__ == "__main__":
    renderer.add_event_handler(trigger, "double_click")
    canvas.request_draw(animate)
    run()
```

Tried with both `pygfx` `0.2.0` and current `main`.

**Comment by panxinmiao** [comment]
This issue seems to be caused by the misalignment of the time_stamp unit when converting wgpu-py events to pygfx events. 
The time_stamp unit for wgpu-py events is in seconds, while for pygfx, it's in milliseconds.

https://github.com/pygfx/pygfx/blob/87decd72d9bd3eec2c73f0fa709cd5cbe4b41093/pygfx/renderers/wgpu/engine/renderer.py#L812-L815

Adding this code before this should solve the problem: 

`event["time_stamp"] = event["time_stamp"] * 1000`

Or just:

`del event["time_stamp"]`

**Comment by almarklein** [comment]
Wow, I had not realized the pygfx timestamp is in ms ... I'd be in favor to change that to seconds. This is Python, not Qt or JS.
