### ISSUE TITLE
CPU usage question?

### ISSUE THREAD

**Issue by rvanlaar** [pygfx/pygfx#763]
The first example from the guide takes up around 313% cpu. 
Is this expected?

The example in question:
```python
import pygfx as gfx

cube = gfx.Mesh(
    gfx.box_geometry(200, 200, 200),
    gfx.MeshPhongMaterial(color="#336699"),
)

if __name__ == "__main__":
    gfx.show(cube)
```
relevant versions:
python3.11.6
wgpu 0.15.2
pygfx 0.2.0

Other specs:
ubuntu 23.10
Intel i7-8665U
AMD Radeon™ RX 6700 XT

**Comment by almarklein** [comment]
Oh shit, it looks like our little glfw event loop is a bit "intense". Funny enough, I cannot reproduce on Windows; it's like 2% there.

**Comment by almarklein** [comment]
I did some more extensive testing:

| OS+GUI                     | wgpu/cube.py | pygfx/cube.py |
|----------------------------|--------------|---------------|
| Linux Xorg with glfw       | 3%           | 25%           |
| Linux Xorg with PySide6    | 3%           | 25%           |
| Linux Wayland with glfw    | 3%           | 25%           |
| Linux Wayland with PySide6 | -            | -             |
| Windows 11 with glfw       | 1%           | 1%            |
| Windows 11 with PySide6    | 1%           | 1%            |
| MacOS M1 with glfw         | 16%          | 300+%         |
| MacOS M1 with PySide6      | 10%          | 300+%         |

It seems like we do *something* very costly in pygfx somehow, that does not happen in a bare wgpu example. This particularly affects MacOS, but also Linux. Windows seems unaffected. But even bare wgpu seems to use the CPU harder on MacOS than other OSes.

**Comment by almarklein** [comment]
Managed to get a working version of wgpu-native 0.20.0, but that does not solve this issue. The next plan is to turn stuff in pygfx off to make it more like the bare wgpu example, and hopefully discover the culprit along the way ...

**Comment by almarklein** [comment]
I traced this down to `np.linalg.inv`. If I use a pure-Python inv implementatio (like [this](https://stackoverflow.com/a/61741074/2271927) one) instead, the cpu% drops to about 20%. There might be other factors, but this seems like a big one.

It looks related to OpenBlas, which is reportedly very fast because it uses multiple threads. Indeed if I set `OPENBLAS_NUM_THREADS=1`, I can use `np.linalg.inv` and get ±20% cpu.

What I don't get, is why the reported CPU usage is 300% even when it renders at like 5 fps. I checked that `inv()` is called just 2 times per draw.  🤔

**Comment by rvanlaar** [comment]
Can confirm, setting OPENBLAS_NUM_THREADS=1 drops my cpu usage to 20%.

**Comment by Korijn** [comment]
Why would `np.linalg.inv` be called repeatedly even if nothing is changing in the scene?

**Comment by almarklein** [comment]
That one, and the one in `camera.update_projection_matrix()`.

The one you mentioned boils down to `AffineBase._inverse_matrix()` in `transform.py`, I think.

**Comment by Korijn** [comment]
What version of numpy are you both using? I hear this is supposed to be adressed in 2.0

**Comment by rvanlaar** [comment]
You have some good sources. Where did you hear that?

I'm using numpy 1.26.4. Tried using 2.0.0rc2 and can confirm, cpu usage is down to the 15-20% range.

**Comment by Korijn** [comment]
I talked about this problem on a Discord server that Stefan van der Walt attends as well, he mentioned it. Glad to hear this fixes it.

**Comment by almarklein** [comment]
I can also confirm that with numpy 2.0 the problem is gone. Numpy 2.0 is due in about 3 weeks. Nevertheless, there will be quite a few users who have numpy 1.x for a while. Do we want to fix this for numpy 1.0, or are we calling this a "bug" in numpy and urge ppl to use numpy 2?

The fix would simply be using `pinv()` instead of `inv()`, so not a big deal. I'm leaning towards fixing it because 300% cpu usage is quite extreme.

**Comment by almarklein** [comment]
I tried to look into further performance improvements, since it can be observed that pygfx uses considerably more cpu than wgpu. I think there is likely some room for optimizations in `render()`, because I see that rendering with the fps stats add significant to the cpu usage. I did not dig too deep, since we'll rework some of that in #492 anyway.

**Comment by rvanlaar** [comment]
Regarding stats, I wanted to show one extra line in the stats. 
I hope it'll become easier to add stats or write an extra module.

From the documentation it wasn't clear how to make my own stats, so I modified stop() method and used the option to overload stats in the gfx.Display function.

**Comment by almarklein** [comment]
Interesting idea ... Perhaps the stats object can register callback functions to obtain more stats?
